### ISSUE TITLE
Do we need to support header-only mode?

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/libigl#4]
I was reading through the readme and it wasn't clear to me why we need the complexity of supporting both compiled (BTW, precompiled is a bad term to use here since it is strongly associated with precompiled headers) and header-only modes? Specifically, from the description, I understood that the header-only mode is only really suitable for toy projects. I also didn't see any issues mentioned that would force someone to use the header-only mode (a typical such issue would be lack of symbols exporting support). Or am I missing something here?

**Comment by lyrahgames** [comment]
> I was reading through the readme and it wasn't clear to me why we need the complexity of supporting both compiled  and header-only modes?

After adding the precompiled mode besides the already existing header-only mode to the package, I wanted to remove the header-only mode to simplify the build. However, I encountered a few problems:

- None of the `libigl` modules except `core` provide any unit tests to properly check whether the packaged version works correctly. The only possibility for verification is to compile the tutorials and run them manually. To identify flaws and issues during development, I compared the header-only and precompiled versions of all tutorials.
- During the development, the availability of both header-only and precompiled modes made it possible to identify certain issues and separate them into package- and source-based problems.
- The module `imgui` is almost fully working in header-only mode but not in precompiled mode. For other modules that have not been added, yet, this might also be an issue.

So, to support further development of this package, it would unfavorable to remove the header-only mode. Furthermore, the following reasons came to my mind when thinking about the package consumption:

- As of my experience, `libigl` is heavily used as a research library in smaller proof-of-concept toy projects. To require the compilation of the whole library, would be a relatively big overhead for these projects when they only need very few features and a small number of headers to access.
- Officially, `libigl` is strongly "advertised" as header-only library with the option to be precompiled. As a consumer, I would find it confusing not to have the opportunity to use the "advertised" header-only mode. This is indeed not a strong reason.
- Running CI tests, the precompiled mode is not supported on as many target configurations as the header-only mode. If the precompiled mode wouldn't work on a certain target platform, the consumer could still try to use the header-only mode maybe with a subset of features.

> Specifically, from the description, I understood that the header-only mode is only really suitable for toy projects. I also didn't see any issues mentioned that would force someone to use the header-only mode (a typical such issue would be lack of symbols exporting support). Or am I missing something here?

During the packaging, I encountered multiple issues concerning CPU and memory usage when trying to compile the tutorials with the header-only library. Because of this and because build2 as a toolchain offers a proper build system and dependency and configuration management, I decided to make the precompiled mode the default.
Maybe I should more emphasize this in the `README.md`

> (BTW, precompiled is a bad term to use here since it is strongly associated with precompiled headers)

I have chosen to use the term `precompiled` because `libigl` was doing it and at that time I didn't have a better idea. It should not be too big of a deal to change the name. I could rename `config.libigl_core.precompiled` to `config.libigl_core.header_only` and reverse the logic of the variable. Do you have any ideas or suggestions for this?

**Comment by boris-kolpackov** [comment]
Thanks for the detailed explanation. Based on this I think it makes sense to continue offering both modes. Here is what I suggest we do:

1. Add a link to this issue from the `README` file as rationale for why the need to support both modes (I don't think we need to copy the whole story there but in the end it's up to you).

2. Rename the `*.precompiled` options. I actually like `config.libigl_core.header_only` that you suggested. It will also mean that the default value will be `false`, which is more natural for a flag.

**Comment by lyrahgames** [comment]
Thanks for reviewing. I have added your suggestions and published a new package revision. [Here](https://ci.cppget.org/@2897d955-a37d-45b1-85d2-a32433f0d1f6), you can find the up-to-date CI run. For now, I will close this issue but feel free to reopen it.

**Comment by boris-kolpackov** [comment]
FYI, you still use term "precompiled" in the `buildfile`, not sure if you want to fix that (e.g., replace it with "compiled").

**Comment by lyrahgames** [comment]
I tried to find any occurrence of `precompiled` even by running `grep` over all possible files but wasn't able to locate it. Can you tell which specific `buildfile` still contains it?

**Comment by boris-kolpackov** [comment]
In the root `buildfile` there is this line:

> # Inclusion files are only installed when no precompilation is used.

I guess you need to search for `precompil` or some such.

**Comment by lyrahgames** [comment]
> I guess you need to search for `precompil` or some such.

Thanks. I think that I was able to find every occurrence and remove and reformulate sentences.
